name: mega_bazar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.1
  firebase_storage: ^11.2.5
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^6.0.0
  flutter_svg: ^2.0.6
  flutter_screenutil: ^5.8.4
  easy_localization: ^3.0.2
  shared_preferences: ^2.1.2
  zoom_tap_animation: ^1.1.0
  http: ^1.1.0
  cached_network_image: ^3.2.3
  provider: ^6.0.5
  lottie: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/svg/
    - assets/translations/
    - assets/lotties/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf

